"""
Lead Analyst Agent module for strategy synthesis and directive generation.

This module defines the Lead Analyst Agent, which applies a strict Logic Matrix
to the Master State to generate final trading directives.
"""
import json
import os
import httpx
from datetime import datetime
from pydantic_ai import RunContext, ModelRetry
from config.agent_factory import create_agent
from models.models import MasterState, FinalDirective
from deps.dependencies import CryptoDependencies

# Define the Lead Analyst Agent with explicit types
analyst_agent = create_agent(
    model_name="openai/gpt-4o",
    system_prompt=(
        "You are the Lead Investment Analyst. Your task is to synthesize technical, macro, "
        "on-chain, and sentiment data from the provided MasterState.\n\n"
        "### STRICT LOGIC MATRIX\n"
        "You MUST apply these boolean checks to generate the Final Directive:\n\n"
        "1. **Macro Veto**:\n"
        "   - IF macro.macro_regime == 'Risk_Off' AND technical.module_1_price_structure.metrics.regime == 'Trending_Up':\n"
        "   - THEN directive = 'Neutral' (Macro overrides Technicals).\n\n"
        "2. **Structure Priority**:\n"
        "   - IF technical.module_1_price_structure.metrics.regime == 'Trending_Up' AND fundamental.module_4_sentiment.sentiment_signal == 'Sell':\n"
        "   - THEN IGNORE sentiment (Trend > Contrarian Signal).\n\n"
        "3. **Liquidity Filter**:\n"
        "   - IF technical.module_5_market_microstructure.squeeze_risk == 'High' OR technical.module_5_market_microstructure.funding_rate_bias == 'Extreme':\n"
        "   - THEN you MUST explicitly mention reducing exposure in your thesis_summary.\n\n"
        "Your goal is to populate the structured FinalDirective output according to these rules."
    ),
    deps_type=CryptoDependencies,
    result_type=FinalDirective
)

@analyst_agent.tool
def get_master_state(ctx: RunContext[CryptoDependencies]) -> dict:
    """Loads the aggregated market state for analysis.

    Reads the `master_state.json` file generated by the Coordinator Agent.

    Args:
        ctx: PydanticAI context.

    Returns:
        dict: The loaded master state data.

    Raises:
        ModelRetry: If the master state file is not found.
    """
    master_path = "data/master_state.json"
    if not os.path.exists(master_path):
        raise ModelRetry("master_state.json not found. Ensure the Coordinator Agent has run.")
        
    with open(master_path, "r") as f:
        return json.load(f)

from tenacity import (
    retry,
    stop_after_attempt,
    wait_exponential,
    retry_if_exception_type,
)

# Define a custom exception for rate limiting
class RateLimitError(Exception):
    """Exception raised when the LLM API returns a 429 Rate Limit error."""
    pass

@analyst_agent.output_validator
async def validate_analyst_output(
    ctx: RunContext[CryptoDependencies],
    output: FinalDirective,
) -> FinalDirective:
    """Validates the Analyst's output for sufficient reasoning detail.

    Ensures the 'thesis_summary' is descriptive enough to provide 
    meaningful insights.

    Args:
        ctx: PydanticAI run context.
        output: The directive model generated by the agent.

    Returns:
        FinalDirective: The validated output model.

    Raises:
        ModelRetry: If the thesis summary is too short.
    """
    if len(output.thesis_summary) < 50:
        raise ModelRetry("Your thesis summary is too brief. Please provide a more detailed logic breakdown.")
    return output

@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10),
    retry=retry_if_exception_type(RateLimitError),
)
async def run_analyst_agent() -> FinalDirective:
    """Runs the Lead Analyst Agent with retry logic and dependency injection.

    Synthesizes the market state using a strict Logic Matrix and produces
    the final trading directive. Implements exponential backoff for 
    rate limit handling.

    Returns:
        FinalDirective: The final synthesis and trading directive.

    Raises:
        RateLimitError: If rate limits are exceeded after retries.
        Exception: For other agent execution failures.
    """
    async with httpx.AsyncClient() as client:
        deps = CryptoDependencies(
            http_client=client,
            user_context={"request_id": "analyst-001"}
        )
        
        try:
            result = await analyst_agent.run(
                "Synthesize the current market state and generate a final directive. "
                "Use the get_master_state tool.",
                deps=deps
            )
            
            # Populate metadata (date) post-execution
            result.data.report_metadata.date = datetime.utcnow().strftime("%Y-%m-%d")
            
            # Legacy compatibility / File persistence
            os.makedirs("reports", exist_ok=True)
            date_str = datetime.utcnow().strftime("%Y%m%d")
            report_path = f"reports/FINAL_DIRECTIVE_{date_str}.json"
            with open(report_path, "w") as f:
                json.dump(result.data.model_dump(), f, indent=2, default=str)
                
            return result.data
            
        except Exception as e:
            if "429" in str(e):
                raise RateLimitError(str(e))
            print(f"Error in analyst_agent: {e}")
            raise

if __name__ == "__main__":
    import asyncio
    
    async def main():
        data = await run_analyst_agent()
        print(data.model_dump_json(indent=2))
        
    asyncio.run(main())
